remove omop_cdm.json

diff --git a/.github/workflows/build_validation.yml b/.github/workflows/build_validation.yml
--- a/.github/workflows/build_validation.yml
+++ b/.github/workflows/build_validation.yml
@@ -28,20 +28,11 @@ jobs:
               - 'infra/**'
             main_json:
               - 'infra/arm_output/main.json'
-            omop_cdm:
-              - 'infra/omop_cdm.bicep'
-            omop_cdm_json:
-              - 'infra/arm_output/omop_cdm.json'
 
-      - name: "Stale json file: main"
+      - name: "Stale ARM Template"
         if: ${{ steps.filter.outputs.main == 'true' &&
           steps.filter.outputs.main_json == 'false' }}
-        run: echo "::error::Code update without updating main.json" && exit 1
-
-      - name: "Stale json file: omop_cdm.json"
-        if: ${{ steps.filter.outputs.omop_cdm == 'true' &&
-          steps.filter.outputs.omop_cdm_json == 'false' }}
-        run: echo "::error::Code update without updating omop_cdm.json" && exit 1
+        run: echo "::error::Stale ARM Template, please regenerate." && exit 1
 
       # MegaLinter
       - name: Lint code base
